# Generated by Django 5.1 on 2025-11-28 08:28

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurationSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('stock_dimensions', models.JSONField()),
                ('parts_spec', models.JSONField()),
                ('config_params', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'configuration_sets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PartSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('W1', models.FloatField(help_text='Wider width in mm', validators=[django.core.validators.MinValueValidator(0.0)])),
                ('W2', models.FloatField(help_text='Narrower width in mm', validators=[django.core.validators.MinValueValidator(0.0)])),
                ('D', models.FloatField(help_text='Length in mm', validators=[django.core.validators.MinValueValidator(0.0)])),
                ('thickness', models.FloatField(help_text='Thickness in mm', validators=[django.core.validators.MinValueValidator(0.0)])),
                ('alpha', models.FloatField(help_text='Taper angle in degrees', validators=[django.core.validators.MinValueValidator(0.0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'part_specifications',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StockBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('length', models.FloatField(help_text='Length in mm', validators=[django.core.validators.MinValueValidator(0.0)])),
                ('width', models.FloatField(help_text='Width in mm', validators=[django.core.validators.MinValueValidator(0.0)])),
                ('height', models.FloatField(help_text='Height in mm', validators=[django.core.validators.MinValueValidator(0.0)])),
                ('material_type', models.CharField(default='Generic', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'stock_blocks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CuttingJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('stock_dimensions', models.JSONField(help_text='Stock block dimensions {length, width, height}')),
                ('parts_spec', models.JSONField(help_text='List of parts with quantities and dimensions')),
                ('config_params', models.JSONField(blank=True, default=dict, help_text='Configuration parameters')),
                ('results', models.JSONField(blank=True, help_text='Optimization results', null=True)),
                ('visualization_files', models.JSONField(blank=True, default=list, help_text='List of visualization file paths')),
                ('report_files', models.JSONField(blank=True, default=list, help_text='List of report file paths')),
                ('export_files', models.JSONField(blank=True, default=list, help_text='List of export file paths (STL, STEP, etc.)')),
                ('stock_block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='planner.stockblock')),
            ],
            options={
                'db_table': 'cutting_jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('primary_part_name', models.CharField(help_text='Primary part type used', max_length=100)),
                ('merging_plane_order', models.CharField(help_text='Merging plane order (e.g., XY-X)', max_length=50)),
                ('stock_dimensions', models.JSONField(help_text='Stock block dimensions')),
                ('parts_spec', models.JSONField(help_text='List of parts used')),
                ('config_params', models.JSONField(blank=True, default=dict)),
                ('total_parts', models.IntegerField(default=0)),
                ('total_volume_used', models.FloatField(default=0.0)),
                ('waste_percentage', models.FloatField(default=0.0)),
                ('is_extractable', models.BooleanField(default=False)),
                ('parts_breakdown', models.JSONField(default=dict, help_text='Count of each part type placed')),
                ('placements', models.JSONField(blank=True, default=list, help_text='Detailed part placements')),
                ('visualization_file', models.CharField(blank=True, help_text='Path to Plotly HTML visualization', max_length=500)),
                ('configuration_set', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='configurations', to='planner.configurationset')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='configurations', to='planner.cuttingjob')),
            ],
            options={
                'db_table': 'configurations',
                'ordering': ['waste_percentage', '-total_parts'],
                'indexes': [models.Index(fields=['waste_percentage', 'total_parts'], name='configurati_waste_p_29428d_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='cuttingjob',
            index=models.Index(fields=['status', 'created_at'], name='cutting_job_status_f28de1_idx'),
        ),
    ]
