# Generated by Django 5.2.8 on 2025-12-18 07:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OptimizationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(default='Untitled Optimization', max_length=255)),
                ('uploaded_file_name', models.CharField(max_length=500)),
                ('uploaded_file_data', models.JSONField(default=list, help_text='Processed Excel data from upload')),
                ('selected_blocks', models.JSONField(default=list, help_text='Blocks selected by user')),
                ('selected_parents', models.JSONField(default=list, help_text='Parent blocks selected')),
                ('parameters', models.JSONField(default=dict, help_text='Buffer spacing, etc.')),
                ('optimization_results', models.JSONField(blank=True, help_text='Full optimization results', null=True)),
                ('efficiency', models.FloatField(default=0.0)),
                ('total_blocks_created', models.IntegerField(default=0)),
                ('total_parts_packed', models.IntegerField(default=0)),
                ('total_parts_requested', models.IntegerField(default=0)),
                ('block_visualization_urls', models.JSONField(blank=True, default=list)),
                ('scrap_visualization_urls', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='optimization_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'optimization_history',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='optimizatio_user_id_24f68f_idx'), models.Index(fields=['efficiency'], name='optimizatio_efficie_976b34_idx')],
            },
        ),
    ]
