# Generated by Django 5.2.8 on 2025-12-18 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_optimizationhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='optimizationhistory',
            name='prism_summary',
            field=models.JSONField(blank=True, default=list, help_text='Summary of prism objects'),
        ),
    ]
